// src/components/WelcomeScreen.tsx
import { IconHistory } from '@tabler/icons-react';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';

interface Props {
  recentFiles: string[];
  onOpenRecent: (path: string) => void;
}

function baseName(path: string): string {
  return path.split(/[\\/]/).pop() ?? path;
}

export default function WelcomeScreen({ recentFiles, onOpenRecent }: Props) {
  return (
    <div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center p-8">
      {recentFiles.length === 0 ? (
        <div className="flex flex-col items-center gap-2 text-muted-foreground">
          <IconHistory size={28} stroke={1.5} />
          <p className="text-sm">No recent files yet</p>
        </div>
      ) : (
        <div className="pointer-events-auto w-full max-w-[340px]">
          <p className="mb-2 px-2.5 text-xs text-muted-foreground">
            Recent files
          </p>
          <ScrollArea className="max-h-80">
            <ul className="flex flex-col gap-1">
              {recentFiles.map((path) => (
                <li key={path}>
                  <Button
                    variant="outline"
                    onClick={() => onOpenRecent(path)}
                    className="h-auto w-full flex-col items-start gap-0.5 px-2.5 py-2 text-left"
                  >
                    <span className="w-full truncate text-sm font-medium text-foreground">
                      {baseName(path)}
                    </span>
                    <span className="w-full truncate text-xs text-muted-foreground">
                      {path}
                    </span>
                  </Button>
                </li>
              ))}
            </ul>
          </ScrollArea>
        </div>
      )}
    </div>
  );
}

// src/components/WelcomeScreen.svelte
<script lang="ts">
  interface Props {
    recentFiles: string[];
    onOpenRecent: (path: string) => void;
  }

  let { recentFiles, onOpenRecent }: Props = $props();

  function baseName(path: string): string {
    return path.split(/[\\/]/).pop() ?? path;
  }
</script>

{#if recentFiles.length > 0}
  <div class="welcome">
    <p class="hint">Recent files</p>
    <ul>
      {#each recentFiles as path (path)}
        <li>
          <button onclick={() => onOpenRecent(path)}>
            <span class="name">{baseName(path)}</span>
            <span class="path">{path}</span>
          </button>
        </li>
      {/each}
    </ul>
  </div>
{/if}

<style>
  .welcome {
    position: absolute;
    inset: 0;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    pointer-events: none;
  }

  .hint {
    opacity: 0.5;
    font-size: 12px;
    margin: 0 0 8px;
  }

  ul {
    list-style: none;
    margin: 0;
    padding: 0;
    width: 340px;
    max-width: 80%;
    pointer-events: auto;
  }

  li + li {
    margin-top: 4px;
  }

  button {
    width: 100%;
    text-align: left;
    background: transparent;
    border: 1px solid var(--editor-active-line);
    border-radius: 4px;
    padding: 8px 10px;
    color: var(--editor-fg);
    cursor: pointer;
    display: flex;
    flex-direction: column;
    gap: 2px;
    font-family: inherit;
  }

  button:hover {
    background-color: var(--editor-active-line);
  }

  .name {
    font-size: 13px;
  }

  .path {
    font-size: 11px;
    opacity: 0.5;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
</style>
